// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "white": "rgba(255, 255, 255, 1)",
 "red01": "rgba(249, 90, 90, 1)",
 "blue06": "rgba(242, 248, 255, 1)",
 "blue05": "rgba(217, 235, 255, 1)",
 "blue04": "rgba(178, 215, 255, 1)",
 "blue03": "rgba(127, 188, 255, 1)",
 "blue02": "rgba(64, 155, 255, 1)",
 "blue01": "rgba(0, 122, 255, 1)",
 "blue": "rgba(0, 90, 189, 1)",
 "black06": "rgba(243, 243, 243, 1)",
 "black05": "rgba(220, 220, 220, 1)",
 "black04": "rgba(185, 185, 185, 1)",
 "black03": "rgba(139, 139, 139, 1)",
 "black02": "rgba(81, 81, 81, 1)",
 "black01": "rgba(35, 35, 35, 1)",
 "black": "rgba(0, 0, 0, 1)"
} as const;

export default colors;