// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "sub": "0.75rem",
 "paragraph": "1rem",
 "h6": "1.25rem",
 "h5": "1.5rem",
 "h4": "2.125rem",
 "h3": "3rem",
 "h2": "3.75rem",
 "h1": "6rem"
} as const;

export default fontSizes;