// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "bold": "DM Sans",
 "medium": "DM Sans",
 "regular": "DM Sans",
 "light": "DM Sans"
} as const;

export default fontFamilies;